version: "3"
services:
  db_cafe: 
    image: postgres:15
    container_name: db_cafe
    env_file:
      - .env
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=123456"
      - "POSTGRES_DB=db_cafe"
      - "TZ=America/Sao_Paulo"
    ports:
      - 5467:5432
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    restart: always
  api_cafe:
    build: .
    container_name: api_cafe
    env_file:
      - .env
    depends_on:
      - db_cafe
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./:/usr/app
    restart: always
    command: sh -c "yarn install && yarn run dev"